version: "3.8"
services:
  caddy-gen:
    container_name: caddy2-gen
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoami
      - whoami2
    labels:
      - "caddy.global=on_demand_tls { ask http://0.0.0.0 }"

  whoami:
    image: "katacoda/docker-http-server:v1"
    labels:
      - "caddy.host=test1.localhost"

  whoami2:
    image: "katacoda/docker-http-server:v2"
    labels:
      - "caddy.host=local" # your domain
      # - "caddy.alias=www.myapp.com" # alias for your domain (optional)
      - "caddy.port=80" # exposed port of this container
      - "caddy.tls.email=admin@myapp.com" # ssl is now on
      - 'caddy.tls.config=on_demand'
